sudo: required

language: generic

services:
  - docker

env:
  global:
    - CI_SOURCE_PATH=$(pwd)

before_install:
  - docker pull kadyncbr/xenial
script:
  - cd /tmp
  - cp -r $CI_SOURCE_PATH ./
  - docker run --rm -it --privileged -v /tmp:/tmp kadyncbr/xenial /bin/sh -c "cd /tmp/stratos_core; cmake .; make"
