sudo: required

language: cpp

services:
  - docker

env:
  global:
    - CI_SOURCE_PATH=$(pwd)

before_install:
  - docker pull kadyncbr/xenial
  - cd /tmp
  - cp -r $CI_SOURCE_PATH ./
  - docker run --privileged -v/tmp:/tmp kadyncbr/xenial /bin/sh -c "cmake .; make"
